### ISSUE TITLE
Not able to signUp and login

### ISSUE THREAD

**Issue by tenze** [ga-diamonds-project3/project-3#24]
I am not able to register and logIn user. keeps giving me 404 error " POST http://localhost:3000/api/users 404 (Not Found) "  which points towards
<img width="560" alt="screen shot 2016-11-28 at 8 40 19 am" src="https://cloud.githubusercontent.com/assets/22038709/20670312/5a4d529a-b546-11e6-909a-0326a14d4d8f.png">

My File Structure
<img width="577" alt="screen shot 2016-11-28 at 8 46 23 am" src="https://cloud.githubusercontent.com/assets/22038709/20670520/2f218162-b547-11e6-88df-835f4cbdb809.png">

@gittheking @jasonseminara @trevorpreston @rapala61 @irwin

**Comment by gittheking** [comment]
@tenze could you please add/commit all the work you currently have right now so I can see what is going on with your user routes. So you don't mess with your teammates work you can push it up to your own branch with:
```
git push origin tenzin-branch
```

**Comment by tenze** [comment]
@gittheking https://github.com/tenze/project-3/tree/react3
Hi bobby this is my branch. I have updated the branch. 
thanks

**Comment by rapala61** [comment]
lets chat

**Comment by rapala61** [comment]
close it please

**Comment by tenze** [comment]
issue resolved
